# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/app.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setIconSize(QtCore.QSize(128, 128))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageArea = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageArea.sizePolicy().hasHeightForWidth())
        self.imageArea.setSizePolicy(sizePolicy)
        self.imageArea.setScaledContents(False)
        self.imageArea.setAlignment(QtCore.Qt.AlignCenter)
        self.imageArea.setObjectName("imageArea")
        self.verticalLayout.addWidget(self.imageArea)
        self.creditsLabel = QtWidgets.QLabel(self.centralwidget)
        self.creditsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.creditsLabel.setOpenExternalLinks(True)
        self.creditsLabel.setObjectName("creditsLabel")
        self.verticalLayout.addWidget(self.creditsLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.getWallpaperButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getWallpaperButton.sizePolicy().hasHeightForWidth())
        self.getWallpaperButton.setSizePolicy(sizePolicy)
        self.getWallpaperButton.setMinimumSize(QtCore.QSize(0, 36))
        self.getWallpaperButton.setObjectName("getWallpaperButton")
        self.horizontalLayout.addWidget(self.getWallpaperButton)
        self.setWallpaperButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setWallpaperButton.sizePolicy().hasHeightForWidth())
        self.setWallpaperButton.setSizePolicy(sizePolicy)
        self.setWallpaperButton.setMinimumSize(QtCore.QSize(0, 36))
        self.setWallpaperButton.setObjectName("setWallpaperButton")
        self.horizontalLayout.addWidget(self.setWallpaperButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GNOME Wallpaper"))
        self.imageArea.setText(_translate("MainWindow", "Wallpaper image will be shown here!"))
        self.creditsLabel.setText(_translate("MainWindow", "Captured by"))
        self.getWallpaperButton.setText(_translate("MainWindow", "Get Wallpaper!"))
        self.setWallpaperButton.setText(_translate("MainWindow", "Set Wallpaper!"))
import src_rc
